language: android

notifications:
  email: false

sudo: false

os:
  - linux
  - osx
node_js:
  - '6'
  - '8'
  - '10'

branches:
  only:
  - master

install:
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0
